### ISSUE TITLE
INim doens not show results of long computations

### ISSUE THREAD

**Issue by andreaferretti** [inim-repl/INim#94]
The first thing I try in a REPL is a slow Fibonacci function, to check that it is not recomputing everything on each new input. So I run

```
nim> proc fib(n: int): int =
....   if n <= 1: n else: fib(n-1) + fib(n-2)
```

and then proceed to ask for

```
nim> fib(6)
8  : int
```

So far, so good. Then I enter

```
nim> fib(40)
```

which just returns the prompt withou giving any result. Every further input takes a few seconds and then it does not give any result.

I am not sure whether `fib(40)` overflows (if I recall correctly, it doesn't) or INim delegates computation to a thread that is killed after a few seconds. In any case, the behaviour of not getting any result back is strange

**Comment by AndreiRegiani** [comment]
I got no issues running your snippet.

```
👑 INim 0.5.0
Nim Compiler Version 1.2.2 [Linux: amd64] at /home/user2/.nimble/bin/nim
nim> proc fib(n: int): int =
....   if n <= 1: n else: fib(n-1) + fib(n-2)
....
nim> fib(6)
8 == type int
nim> fib(40)
102334155 == type int
nim> fib(10)
55 == type int
nim>
```
Try running in a standalone .nim file.

>it does not give any result.
While using INim check `/tmp/inim_*.nim`, that's what INim compiles and
shows you, we do count & filter the output you've already seen, so that
could be the problem.

Now unrelated to INim:

`fib(40)` took 3.42s on an Intel i7-8550U 1.8-4.0GHz.
That does 331 million `fib()` calls.

`fib(50)` took 9.3 minutes, doing 40 billion `fib()` calls, any input
beyond 50 will take forever to finish.
The thing is your algorithm is exponentially slow.

**Comment by andreaferretti** [comment]
This is my output

```
andrea$ inim
👑 INim 0.5.0
Nim Compiler Version 1.3.5 [MacOSX: amd64] at /Users/andrea/.mynim/bin/nim
nim> proc fib(n: int): int =
....   if n <= 1: n else: fib(n-1) + fib(n-2)
....   
nim> fib(6)
8  : int
nim> fib(40)
nim> exit
```
> Try running in a standalone .nim file.

Here it works, but I have to add an `echo` of course, since a standalone nim file does not evaluate expressions. Adding an `echo` also works in the shell

> The thing is your algorithm is exponentially slow.

This is *intentional*. I was testing a slow computation on purpose, to see if everything is recomputed fron scratch on every new statement that I enter. If this is the case, a shell buys me little over just compiling a file myself, so my test was checking that entering, say, `2+2` after a computation that takes time is essentially instantaneous.

**Comment by Tangdongle** [comment]
@andreaferretti There are issues with using devel currently, see https://github.com/inim-repl/INim/issues/89. I'm not sure why, yet

**Comment by Tangdongle** [comment]
I don't think this is an issue anymore. I can recreate it and it properly prints the expected output. This should also work in devel now, INim was incompatible was devel when you raised this (and was super shaky with the type output as you can see in your original example, ie `8  : int` as opposed to `8 == type int`) , but that has since been fixed.

Runs on latest and devel:
`ryan at rypad in ~
$ inim    
👑 INim 0.6.0
Nim Compiler Version 1.2.6 [Linux: amd64] at /home/ryan/.nimble/bin/nim
nim> proc fib(n: int): int =
....   if n <= 1: n else: fib(n-1) + fib(n-2)
....   
nim> fib(6)
8 == type int
nim> fib(40)
102334155 == type int
nim> 
`

@0atman I believe this can be closed with https://github.com/inim-repl/INim/pull/99 (technically a few prior commits fixing devel compatibility, but this one proves it best)

**Comment by andreaferretti** [comment]
(what does `8 == type int` even mean?)

**Comment by 0atman** [comment]
just the way we were printing it's type, I guess?

**Comment by andreaferretti** [comment]
Well, it's a strange way to print types, isn't it? `8: int` was much more clear, as it is the way to declare types in Nim. `8 == type int` is strange because, well, 8 is not the type of the type int. Rather, `int == type 8` is a true equality, as well as `typedesc[int] == type int`.
